import { chromium } from 'playwright-core';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 700, height: 800 } });
await p.addInitScript(() => { try { localStorage.setItem('welcome-seen','1'); } catch {} });
await p.goto('http://localhost:3235/phones', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(2000);
const card = p.locator('a.group').nth(1);
await card.scrollIntoViewIfNeeded();
const media = card.locator('div').first();
console.log('media class:', await media.evaluate(el => el.className));
console.log('media transition:', await media.evaluate(el => getComputedStyle(el).transitionProperty + ' / ' + getComputedStyle(el).transitionDuration));
const box = await card.boundingBox();
await p.mouse.move(box.x + box.width/2, box.y + 120);
await p.waitForTimeout(700);
console.log('LINK transform on hover:', await card.evaluate(el => getComputedStyle(el).transform));
console.log('MEDIA transform on hover:', await media.evaluate(el => getComputedStyle(el).transform));
console.log('media matches :hover ancestor?', await media.evaluate(el => el.closest('.group').matches(':hover')));
await b.close();
